# Site settings
title: Jekyll Maps
email: matthews.sam@gmail.com
description: Point-based map engine generated via static Jekyll posts.
baseurl: "/jekyll-maps/" # the subpath of your site, e.g. /blog/
url: "http://mapsam.com/jekyll-maps/" # the base hostname & protocol for your site
twitter_username: vancematthews
github_username:  svmatthews

# Build settings
markdown: kramdown
