# Site settings
title: "Los Angeles: The City and the Library"
email: kirschbombe@gmail.com
description:
baseurl: "/flaneur" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: kirschbombe
github_username:  kirschbombe

# Build settings
markdown: kramdown
encoding: utf-8

# Map
# map-tileset: 'https://{s}.tiles.mapbox.com/v3/kirschbombe.l007nm13/{z}/{x}/{y}.png'
map-tileset: 'https://{s}.tiles.mapbox.com/v3/kirschbombe.ae0a59b5/{z}/{x}/{y}.png'
map-credits: '<a target="_blank" href="https://github.com/kirschbombe/flaneur">Fl√¢neur</a> | Tiles: Mapbox'

#leaflet settings
minZoom: 0
maxZoom: 20
#<LatLng> center, <Number> zoom, <Zoom/pan options> options?), 
#see http://leafletjs.com/reference-1.2.0.html for more info
setView: '[34.0253, -118.3085], 1'


collections:
  posts:
    output: true
    permalink: /article/:name
  article-index:
    title: Article Index
    output: true
    permalink: /article-index/:name/

permalink: /:categories/:title/

# menu options: dropdown, circle
menu-type: dropdown

# settings for circle menu
menu-height: '200px'
menu-width: '200px'
menu-opacity: '.95'

#pages to exclude in menu
exclude_pages: [ "index.html", 'home.md']

#accent color can be any css accepted value
accent_color: rgba(25, 87, 142, 1)

#